[package]
name = "bitpart-cli"
version = "0.1.0"
authors = ["Josh King <josh@throneless.tech>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
futures-util = "0.3.31"
http = "1.2.0"
serde_json = "1.0.132"
tokio = { version = "1.43.0", features = ["full"] }
tokio-tungstenite = { version = "0.26.1", features = ["url"] }
url = "2.5.4"

[dev-dependencies]
