[package]
name = "bitpart-cli"
version = "0.1.0"
authors = ["Josh King <josh@throneless.tech>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
clap-verbosity-flag = "2.2.2"
config = { version = "0.14", features = ["toml"] }
directories = "5.0"
log = "0.4"
pretty_env_logger = "0.5"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
serde_json = "1.0.132"

[dev-dependencies]
rusty-hook = "^0.11"
trybuild = "1.0"
trycmd = "0.15"
