[package]
name = "bitpart-cli"
version = "0.1.0"
authors = ["Josh King <josh@throneless.tech>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
axum = { version = "0.8.1", features = ["ws"] }
bytes = "1.9.0"
clap = { version = "4", features = ["derive"] }
clap-verbosity-flag = "2.2.2"
config = { version = "0.14", features = ["toml"] }
csml_interpreter = { git = "https://github.com/throneless-tech/csml-engine", branch = "bitpart" }
directories = "5.0"
futures-util = "0.3.31"
http = "1.2.0"
log = "0.4"
pretty_env_logger = "0.5"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.132"
tokio = { version = "1.43.0", features = ["full"] }
tokio-tungstenite = { version = "0.26.1", features = ["url"] }
url = "2.5.4"

[dev-dependencies]
rusty-hook = "^0.11"
trybuild = "1.0"
trycmd = "0.15"
