[package]
name = "presage-store-bitpart"
version = "0.6.0-dev"
edition = "2021"
authors = ["Gabriel Féron <g@leirbag.net>"]
license = "AGPL-3.0-only"

[dependencies]
async-trait = "0.1"
base64 = "0.22"
chrono = "0.4.35"
fs_extra = "1.3"
presage = { git = "https://github.com/whisperfish/presage" }
presage-store-cipher = { optional = true, git = "https://github.com/whisperfish/presage" }
prost = "0.13"
quickcheck_macros = "1.0.0"
sea-orm = { version = "~1.0", features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
thiserror = "1.0"
tokio = "1.35"
tracing = "0.1"
uuid = "1.11.0"

[build-dependencies]
prost-build = "0.13"

[dev-dependencies]
anyhow = "1.0"
quickcheck = "1.0.3"
quickcheck_async = "0.1"
rand = "0.8"
tokio = { version = "1.35", default-features = false, features = ["time"] }

[features]
default = ["encryption"]
encryption = ["dep:presage-store-cipher"]
