[package]
name = "bitpart-plugin"
version = "0.1.0"
authors = ["Josh King <josh@throneless.tech>"]
edition = "2021"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
cglue = { version = "0.3.4", features = ["layout_checks"] }
abi_stable = "0.10"
libloading = "0.7"
